2025-02-20 17:23:47.556 [info] Telemetry level is off
2025-02-20 17:23:47.556 [info] Experiments are disabled, only manually opted experiments are active.
2025-02-20 17:23:47.556 [debug] Reading directory failed [Error: ENOENT: no such file or directory, scandir '/home/kyle/dev/.pixi/envs'
	at Object.readdirSync (node:fs:1506:26)
	at t.readdirSync (node:electron/js2c/node_init:2:13703)
	at /usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:709712
	at /usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:709892
	at Array.map (<anonymous>)
	at m.initWatchers (/usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:709621)
	at async m.ensureWatchersReady (/usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:663315)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/kyle/dev/.pixi/envs'
}
2025-02-20 17:23:47.556 [warning] Dir "/home/kyle/dev/.pixi/envs" is not watchable (directory does not exist)
2025-02-20 17:23:47.556 [debug] Start watching file for changes /home/kyle/.conda/environments.txt
2025-02-20 17:23:47.556 [debug] Start watching: /home/kyle/.conda with pattern environments.txt using VSCode API
2025-02-20 17:23:47.556 [debug] Start watching root /home/kyle/dev for globs ["python","*/python","*/bin/python"]
2025-02-20 17:23:47.556 [debug] Start watching: /home/kyle/dev with pattern python using VSCode API
2025-02-20 17:23:47.556 [debug] Start watching: /home/kyle/dev with pattern */python using VSCode API
2025-02-20 17:23:47.556 [debug] Start watching: /home/kyle/dev with pattern */bin/python using VSCode API
2025-02-20 17:23:47.556 [debug] Testing: Setting up watcher for /home/kyle/dev
2025-02-20 17:23:47.556 [info] Starting Environment refresh
2025-02-20 17:23:47.557 [info] Searching for interpreters in posix paths locator
2025-02-20 17:23:47.557 [info] Searching for pyenv environments
2025-02-20 17:23:47.557 [info] Searching for conda environments
2025-02-20 17:23:47.557 [debug] Searching for conda.
2025-02-20 17:23:47.557 [info] Searching for global virtual environments
2025-02-20 17:23:47.557 [info] Searching for custom virtual environments
2025-02-20 17:23:47.557 [info] activatePositron: done!
2025-02-20 17:23:47.557 [debug] Probing conda binary: conda
2025-02-20 17:23:47.557 [debug] Searching for custom workspace envs
2025-02-20 17:23:47.557 [debug] Probing Hatch binary hatch
2025-02-20 17:23:47.557 [debug] Finished searching for custom workspace envs
2025-02-20 17:23:47.557 [info] pyenv is not installed
2025-02-20 17:23:47.557 [info] Finished searching for pyenv environments: 15 milliseconds
2025-02-20 17:23:47.557 [info] Finished searching for custom virtual envs: 14 milliseconds
2025-02-20 17:23:47.557 [debug] Couldn't locate the state binary.
2025-02-20 17:23:47.557 [info] > conda info --json
2025-02-20 17:23:47.557 [debug] Failed to spawn conda binary conda [Error: spawn conda ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:285:19)
	at onErrorNT (node:internal/child_process:483:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'info', '--json' ]
}
2025-02-20 17:23:47.557 [debug] Searching for workspace virtual envs in: /home/kyle/dev
2025-02-20 17:23:47.557 [info] > hatch env show --json
2025-02-20 17:23:47.557 [info] cwd: .
2025-02-20 17:23:47.557 [debug] [Error: spawn hatch ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:285:19)
	at onErrorNT (node:internal/child_process:483:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn hatch',
  path: 'hatch',
  spawnargs: [ 'env', 'show', '--json' ]
}
2025-02-20 17:23:47.557 [debug] Failed to find Hatch binary hatch
2025-02-20 17:23:47.557 [debug] No Hatch binary found
2025-02-20 17:23:47.557 [debug] Finished searching for Hatch envs
2025-02-20 17:23:47.557 [debug] Finished searching for poetry envs
2025-02-20 17:23:47.557 [debug] Needed to validate /bin/python3 with latest info
2025-02-20 17:23:47.557 [info] Python interpreter path: /bin/python3
2025-02-20 17:23:47.557 [debug] Found cached env for /bin/python3
2025-02-20 17:23:47.557 [info] Finished searching for global virtual envs: 42 milliseconds
2025-02-20 17:23:47.557 [debug] Attempting to resolve symbolic link: /bin/python3
2025-02-20 17:23:47.559 [info] Found: /bin/python3 --> /bin/python3.13
2025-02-20 17:23:47.559 [debug] Attempting to resolve symbolic link: /bin/python3.13
2025-02-20 17:23:47.560 [info] Found: /bin/python3.13 --> /bin/python3.13
2025-02-20 17:23:47.562 [debug] Finished searching for Pixi envs
2025-02-20 17:23:47.562 [debug] Couldn't locate the conda binary.
2025-02-20 17:23:47.562 [debug] Couldn't locate the conda binary.
2025-02-20 17:23:47.593 [info] pythonRuntimeDiscoverer: Starting Python runtime discoverer
2025-02-20 17:23:47.593 [info] pythonRuntimeDiscoverer: recommended interpreter: /bin/python3
2025-02-20 17:23:47.593 [info] pythonRuntimeDiscoverer: sorting interpreters
2025-02-20 17:23:47.593 [info] pythonRuntimeDiscoverer: discovered 2 Python interpreters
2025-02-20 17:23:47.715 [debug] Attempting to resolve symbolic link: /usr/bin/python3
2025-02-20 17:23:48.073 [info] Found: /usr/bin/python3 --> /usr/bin/python3.13
2025-02-20 17:23:48.073 [debug] Attempting to resolve symbolic link: /usr/bin/python3.13
2025-02-20 17:23:48.078 [info] pythonRuntimeDiscoverer: recommended for workspace: false
2025-02-20 17:23:48.078 [info] createPythonRuntime: getting service instances
2025-02-20 17:23:48.078 [info] createPythonRuntime: getting extension runtime settings
2025-02-20 17:23:48.078 [info] createPythonRuntime: checking if ipykernel is installed
2025-02-20 17:23:48.079 [debug] could not find a pixi interpreter for the interpreter at /bin/python3
2025-02-20 17:23:48.163 [debug] Received shell integration sequence for bash
2025-02-20 17:23:48.163 [info] Found: /usr/bin/python3.13 --> /usr/bin/python3.13
2025-02-20 17:23:48.200 [info] > /bin/python3 -I /usr/share/positron/resources/app/extensions/positron-python/python_files/get_output_via_markers.py /usr/share/positron/resources/app/extensions/positron-python/python_files/interpreterInfo.py
2025-02-20 17:23:48.218 [debug] Activation Commands received undefined for shell bash, resource undefined and interpreter /bin/python3
2025-02-20 17:23:48.257 [debug] Found interpreter for >> /bin/python3 -I /usr/share/positron/resources/app/extensions/positron-python/python_files/get_output_via_markers.py /usr/share/positron/resources/app/extensions/positron-python/python_files/interpreterInfo.py <<: {"versionInfo":[3,13,2,"final",0],"sysPrefix":"/usr","sysVersion":"3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0]","is64Bit":true}
2025-02-20 17:23:48.336 [info] > /bin/python3 -c "import ipykernel; print(ipykernel.__version__)"
2025-02-20 17:23:48.403 [debug] Error when getting version of module ipykernel [n [Error]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ipykernel; print(ipykernel.__version__)
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ipykernel'

	at ChildProcess.<anonymous> (/usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:264675)
	at Object.onceWrapper (node:events:633:26)
	at ChildProcess.emit (node:events:518:28)
	at maybeClose (node:internal/child_process:1104:16)
	at Socket.<anonymous> (node:internal/child_process:456:11)
	at Socket.emit (node:events:518:28)
	at Pipe.<anonymous> (node:net:343:12)]
2025-02-20 17:23:48.403 [info] createPythonRuntime: startup behavior: explicit
2025-02-20 17:23:48.403 [info] pythonRuntimeDiscoverer: registering runtime for interpreter /bin/python3 with id 40b7d5eb0365643a3cc6b86cc5c0dcaf
2025-02-20 17:23:48.404 [info] createPythonRuntime: getting service instances
2025-02-20 17:23:48.404 [info] createPythonRuntime: getting extension runtime settings
2025-02-20 17:23:48.404 [info] createPythonRuntime: checking if ipykernel is installed
2025-02-20 17:23:48.404 [debug] could not find a pixi interpreter for the interpreter at /usr/bin/python3
2025-02-20 17:23:48.404 [debug] Finished searching for workspace virtual envs
2025-02-20 17:23:48.450 [debug] Found 2 python binaries in posix paths
2025-02-20 17:23:48.451 [info] Finished searching for interpreters in posix paths locator: 951 milliseconds
2025-02-20 17:23:48.645 [debug] Activation Commands received undefined for shell bash, resource undefined and interpreter /usr/bin/python3
2025-02-20 17:23:48.846 [info] > /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__)"
2025-02-20 17:23:48.923 [debug] Error when getting version of module ipykernel [n [Error]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ipykernel; print(ipykernel.__version__)
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ipykernel'

	at ChildProcess.<anonymous> (/usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:264675)
	at Object.onceWrapper (node:events:633:26)
	at ChildProcess.emit (node:events:518:28)
	at maybeClose (node:internal/child_process:1104:16)
	at Socket.<anonymous> (node:internal/child_process:456:11)
	at Socket.emit (node:events:518:28)
	at Pipe.<anonymous> (node:net:343:12)]
2025-02-20 17:23:48.923 [info] createPythonRuntime: startup behavior: explicit
2025-02-20 17:23:48.923 [info] pythonRuntimeDiscoverer: registering runtime for interpreter /usr/bin/python3 with id b1d530ccd54e9ca908e843bb1a13ac57
2025-02-20 17:23:49.142 [info] > /usr/bin/python3 -I /usr/share/positron/resources/app/extensions/positron-python/python_files/get_output_via_markers.py /usr/share/positron/resources/app/extensions/positron-python/python_files/interpreterInfo.py
2025-02-20 17:23:49.142 [info] Environments refresh paths discovered (event): 1643 milliseconds
2025-02-20 17:23:49.142 [debug] Finished with environment reducer
2025-02-20 17:23:49.142 [info] Environments refresh paths discovered: 1643 milliseconds
2025-02-20 17:23:49.179 [debug] Found interpreter for >> /usr/bin/python3 -I /usr/share/positron/resources/app/extensions/positron-python/python_files/get_output_via_markers.py /usr/share/positron/resources/app/extensions/positron-python/python_files/interpreterInfo.py <<: {"versionInfo":[3,13,2,"final",0],"sysPrefix":"/usr","sysVersion":"3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0]","is64Bit":true}
2025-02-20 17:23:49.179 [info] Environments refresh finished (event): 1680 milliseconds
2025-02-20 17:23:49.180 [debug] Finished with environment resolver
2025-02-20 17:23:49.181 [debug] Python API env change detected /bin/python3 update
2025-02-20 17:23:49.181 [debug] Python API env change detected /usr/bin/python3 update
2025-02-20 17:23:49.181 [debug] Environments added to cache [{"name":"","location":"","kind":"global-other","executable":{"filename":"/bin/python3","sysPrefix":"/usr","ctime":1739932184402,"mtime":1736345761000},"display":"Python 3.13.2 64-bit","version":{"major":3,"minor":13,"micro":2,"release":{"level":"final","serial":0},"sysVersion":"3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0]"},"arch":3,"distro":{"org":""},"source":["path env var"],"id":"/bin/python3","detailedDisplayName":"Python 3.13.2 64-bit"},{"name":"","location":"","kind":"global-other","executable":{"filename":"/usr/bin/python3","sysPrefix":"/usr","ctime":1739932184402,"mtime":1736345761000},"display":"Python 3.13.2 64-bit","version":{"major":3,"minor":13,"micro":2,"release":{"level":"final","serial":0},"sysVersion":"3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0]"},"arch":3,"distro":{"org":""},"source":["path env var"],"id":"/usr/bin/python3","detailedDisplayName":"Python 3.13.2 64-bit"}]
2025-02-20 17:23:49.182 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.182 [info] Environment refresh took 1684 milliseconds
2025-02-20 17:23:49.192 [info] > pyenv which python
2025-02-20 17:23:49.192 [info] cwd: .
2025-02-20 17:23:49.193 [debug] [Error: Command failed: pyenv which python
/bin/sh: 1: pyenv: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:530:35)
	at maybeClose (node:internal/child_process:1104:16)
	at Socket.<anonymous> (node:internal/child_process:456:11)
	at Socket.emit (node:events:518:28)
	at Pipe.<anonymous> (node:net:343:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'pyenv which python'
}
2025-02-20 17:23:49.201 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.202 [error] Failed to get conda envs from environments.txt [TypeError: e.splitLines is not a function
	at /usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:674553
	at async /usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:674503
	at async Promise.all (index 2)
	at async /usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:674224
	at async x.sendTelemetryImpl (/usr/share/positron/resources/app/extensions/positron-python/dist/client/extension.js:2:673615)]
2025-02-20 17:23:49.202 [debug] Needed to validate /usr/bin/python3 with latest info
2025-02-20 17:23:49.233 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.233 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.233 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.233 [info] Editor support is inactive since language server is set to None.
2025-02-20 17:23:49.236 [debug] could not find a pixi interpreter for the interpreter at /bin/python3
2025-02-20 17:23:49.247 [debug] Found cached env for /bin/python3
2025-02-20 17:23:49.256 [debug] Activation Commands received undefined for shell /usr/bin/bash, resource /home/kyle/dev and interpreter /bin/python3
2025-02-20 17:23:49.256 [debug] Activated environment variables for /home/kyle/dev
